Added docstrings to BlueHatGreenHat.py, animal.py, clothing.py.
Meltz014/ChildrensBooks pull request #2
Opened 2020-10-02 18:25 UTC by tim-andes

See title

2020-10-02 20:00 UTC, Meltz014 requested changes

2020-10-02 20:00 UTC, Meltz014 commented on BlueHatGreenHat/BlueHatGreenHat.py
Can you add a module level docstring here that depicts the goal for the program?  I.e. to generate the text of Blue Hat Green Hat by sandra boynton, etc.

2020-10-02 20:00 UTC, Meltz014 commented on BlueHatGreenHat/animal.py
> +        """Upon a swim, any current clothing raises OopsError('Oops!')."""
Swim naked, baby

2020-10-02 20:00 UTC, Meltz014 commented on BlueHatGreenHat/clothing.py
> +    """A simulation of a clothing article with the single attribute, color."""
Can you format the attribute here like you did in BodyPart?

2020-10-02 20:00 UTC, Meltz014 commented on BlueHatGreenHat/animal.py
> +    """A simulation of an animal and its various body parts."""
List the attributes

2020-10-03 12:51 UTC, tim-andes commented
Module level docstrings created per Google Style Guide supplemented by PEP257

2020-10-05 15:01 UTC, merged